"""小企业会计准则科目种子数据(源自 Excel 凭证录入科目表)。

每项:(编码, 名称, 类别, 余额方向)
类别 category: asset/liability/equity/cost/profit
方向 direction: debit 借 / credit 贷
"""

# (code, name, category, direction)
ACCOUNTS: list[tuple[str, str, str, str]] = [
    # ---------- 资产类 ----------
    ("1001", "库存资金", "asset", "debit"),
    ("1002", "银行存款", "asset", "debit"),
    ("1012", "其他货币资金", "asset", "debit"),
    ("1101", "交易性金融资产", "asset", "debit"),
    ("1121", "应收票据", "asset", "debit"),
    ("1122", "应收账款", "asset", "debit"),
    ("1123", "预付账款", "asset", "debit"),
    ("1131", "应收股利", "asset", "debit"),
    ("1132", "应收利息", "asset", "debit"),
    ("1221", "其他应收款", "asset", "debit"),
    ("1231", "坏账准备", "asset", "credit"),
    ("1401", "材料采购", "asset", "debit"),
    ("1403", "原材料", "asset", "debit"),
    ("1404", "材料成本差异", "asset", "debit"),
    ("1405", "库存商品", "asset", "debit"),
    ("1406", "发出商品", "asset", "debit"),
    ("1407", "商品进销差价", "asset", "credit"),
    ("1408", "委托加工物资", "asset", "debit"),
    ("1411", "包装物及低值易耗品", "asset", "debit"),
    ("1471", "存货跌价准备", "asset", "credit"),
    ("1501", "持有至到期投资", "asset", "debit"),
    ("1502", "持有至到期投资减值准备", "asset", "credit"),
    ("1503", "可供出售金融资产", "asset", "debit"),
    ("1511", "长期股权投资", "asset", "debit"),
    ("1512", "长期股权投资减值准备", "asset", "credit"),
    ("1521", "投资性房地产", "asset", "debit"),
    ("1531", "长期应收款", "asset", "debit"),
    ("1601", "固定资产", "asset", "debit"),
    ("1602", "累计折旧", "asset", "credit"),
    ("1603", "固定资产减值准备", "asset", "credit"),
    ("1604", "在建工程", "asset", "debit"),
    ("1605", "工程物资", "asset", "debit"),
    ("1606", "固定资产清理", "asset", "debit"),
    ("1701", "无形资产", "asset", "debit"),
    ("1702", "无形资产减值准备", "asset", "credit"),
    ("1703", "累计摊销", "asset", "credit"),
    ("1711", "商誉", "asset", "debit"),
    ("1801", "长期待摊费用", "asset", "debit"),
    ("1811", "递延所得税资产", "asset", "debit"),
    ("1901", "待处理财产损溢", "asset", "debit"),
    # ---------- 负债类 ----------
    ("2001", "短期借款", "liability", "credit"),
    ("2101", "交易性金融负债", "liability", "credit"),
    ("2201", "应付票据", "liability", "credit"),
    ("2202", "应付账款", "liability", "credit"),
    ("2203", "预收账款", "liability", "credit"),
    ("2211", "应付职工薪酬", "liability", "credit"),
    ("2221", "应交税费", "liability", "credit"),
    ("2231", "应付股利", "liability", "credit"),
    ("2232", "应付利息", "liability", "credit"),
    ("2241", "其他应付款", "liability", "credit"),
    ("2401", "预计负债", "liability", "credit"),
    ("2501", "长期借款", "liability", "credit"),
    ("2502", "长期债券", "liability", "credit"),
    ("2701", "长期应付款", "liability", "credit"),
    ("2711", "专项应付款", "liability", "credit"),
    ("2901", "递延所得税负债", "liability", "credit"),
    # ---------- 所有者权益类 ----------
    ("4001", "实收资本", "equity", "credit"),
    ("4002", "资本公积", "equity", "credit"),
    ("4101", "盈余公积", "equity", "credit"),
    ("4103", "本年利润", "equity", "credit"),
    ("4104", "利润分配", "equity", "credit"),
    ("4201", "库存股", "equity", "debit"),
    # ---------- 成本类 ----------
    ("5001", "生产成本", "cost", "debit"),
    ("5101", "制造费用", "cost", "debit"),
    ("5201", "劳务成本", "cost", "debit"),
    ("5301", "研发支出", "cost", "debit"),
    # ---------- 损益类 ----------
    ("6001", "主营业务收入", "profit", "credit"),
    ("6051", "其他业务收入", "profit", "credit"),
    ("6101", "公允价值变动损益", "profit", "credit"),
    ("6111", "投资收益", "profit", "credit"),
    ("6301", "营业外收入", "profit", "credit"),
    ("6401", "主营业务成本", "profit", "debit"),
    ("6402", "其他业务支出", "profit", "debit"),
    ("6403", "营业税金及附加", "profit", "debit"),
    ("6601", "销售费用", "profit", "debit"),
    ("6602", "管理费用", "profit", "debit"),
    ("6603", "财务费用", "profit", "debit"),
    ("6701", "资产减值损失", "profit", "debit"),
    ("6711", "营业外支出", "profit", "debit"),
    ("6801", "所得税费用", "profit", "debit"),
    ("6901", "以前年度损益调整", "profit", "debit"),
]
